### ISSUE TITLE
Special characters cause invalid key generation

### ISSUE THREAD

**Issue by Fauntleroy** [dmcquay/node-apac#10]
When searching for strings that include special characters it can cause the Amazon API to return an improper key error. 

Attempted "trentemøller" and "trentem%C3%B8ller"

**Comment by dmcquay** [comment]
This is really old so you guys probably don't care about this anymore, but I'm cleaning out some old bugs. I tried the following query and it worked fine:

```
opHelper.execute('ItemSearch', {
    'SearchIndex': 'Music',
    'Keywords': 'trentemøller',
    'ResponseGroup': 'ItemAttributes'
}).then((response) => {
    console.log(JSON.stringify(response.result, null, 2))
})
```
Note that this is using the new `update` branch which should be merged in the next few days, so if you want to try this yourself, you should use that branch.

I'm going to close this issue for now, but if you care still and are still seeing this problem, please send me a specific query to reproduce.
