### ISSUE TITLE
Locale feature

### ISSUE THREAD

**Issue by Hucho** [dmcquay/node-apac#62]
locale: "DE" f.e.

something like this..

function setLocale(locale) {
  if (locale) {
    locale = locale.toUpperCase();
  }

  switch (locale) {
    case 'BR':
      return 'webservices.amazon.com.br';
      break;

    case 'CA':
      return 'webservices.amazon.ca';
      break;

    case 'CN':
      return 'webservices.amazon.cn';
      break;

    case 'FR':
      return 'webservices.amazon.fr';
      break;

    case 'DE':
      return 'webservices.amazon.de';
      break;

    case 'IN':
      return 'webservices.amazon.in';
      break;

    case 'IT':
      return 'webservices.amazon.it';
      break;

    case 'JP':
      return 'webservices.amazon.co.jp';
      break;

    case 'MX':
      return 'webservices.amazon.com.mx';
      break;

    case 'ES':
      return 'webservices.amazon.es';
      break;

    case 'UK':
      return 'webservices.amazon.co.uk';
      break;

    default:
      return 'webservices.amazon.com';
  }
}

**Comment by dmcquay** [comment]
https://github.com/dmcquay/node-apac/pull/66

**Comment by dmcquay** [comment]
This is fixed in v1.4.0 which has been published to npm.

**Comment by Hucho** [comment]
Hi Dustin, I today tested your new api, respectively the promise feature together with the throttling limit. I did not debugged it...but it is not working properly if you inject the querys into the operation execute....
All queries are executed at once...

Best Matthias 

Von meinem iPhone gesendet

**Comment by Hucho** [comment]
I would like to test locale feature...but it is not online?

Best Matthias 

Von meinem iPhone gesendet

**Comment by dmcquay** [comment]
@Hucho - Regarding the throttling feature, did you set the the maxRequestsPerSecond parameter to a positive number? Can you send me your code?

The documentation for the auto-throttling is here:
https://github.com/dmcquay/node-apac#throttling--request-limits

Regarding the locale feature, it is available, both via git and npm. Just install v1.4.0. I apologize I have not yet documented the locale parameter, but you can see how to use it in the tests here:
https://github.com/dmcquay/node-apac/blob/master/lib/operation-helper.specs.js#L33

**Comment by DaanOlbrechts** [comment]
@dmcquay I tried the code on Git yesterday and it works perfectly, but it seems the changes have not been included in the v1.4.0 on npm (I tested that again just now). Maybe that's why others  are having problems with it?

**Comment by dmcquay** [comment]
Thx I will check on yhay

**Comment by dmcquay** [comment]
Thanks @DaanOlbrechts. Indeed that was missing in v1.4.0 for some reason. I have published a new version (1.5.0) that includes the locale changes.

**Comment by dmcquay** [comment]
@Hucho - see prev comment

**Comment by DaanOlbrechts** [comment]
Perfect! Thanks!

**Comment by Hucho** [comment]
Hi Dustin,
I would like to use the German locale setting now; how can I easily change the locale? Do I understand it correctly that I can just set "locale" to "DE" and pass it into the OperationsHelper with my other credentials?

**Comment by dmcquay** [comment]
Yes. See example here: https://github.com/dmcquay/node-apac/blob/master/lib/operation-helper.specs.js#L33
