### ISSUE TITLE
Get rid of annoying arrays in results

### ISSUE THREAD

**Issue by dmcquay** [dmcquay/node-apac#63]
See what HiDAI did here: https://github.com/HiDAl/node-apac/commit/2a1a1ae6d33f8a9a121b63a81b4577ded7767033

I'd like to consider pulling this into the core repo b/c those arrays everywhere are really annoying.

**Comment by bluepuma77** [comment]
+1

**Comment by bluepuma77** [comment]
Found a solution. Would be good to document it in the README.

```
var opHelper = new OperationHelper({
  awsId: '[YOUR AWS ID HERE]',
  awsSecret: '[YOUR AWS SECRET HERE]',
  assocId: '[YOUR ASSOCIATE TAG HERE]',
  xml2jsOptions:  {explicitArray: false}
});
```
