### ISSUE TITLE
How to get more than 10 results?

### ISSUE THREAD

**Issue by bluepuma77** [dmcquay/node-apac#65]
I would like to retrieve 100 results for a keyword search with Amazon's Product Advertising API. By default the number of results is limited to 10 and I understand that paging is required to get more. There is a `MoreSearchResultsUrl` field provided in the response. Is that somehow supported by node-apac?

**Comment by bluepuma77** [comment]
@bullgare [coded something](https://github.com/bullgare/node-apac/commit/c14a38576810eeef2b00799f4ce503af5159bd36) in 2012, but that doesn't seem to work. I tried it with:
```
opHelper.execute('ItemSearch', {
    'SearchIndex': 'Books',
    'Keywords': 'harry potter',
    'ResponseGroup': 'ItemAttributes,Offers',
    'page': '2'
}, function (err, results) {
    console.log(JSON.stringify(results, null, 4))                    
})
```

**Comment by bullgare** [comment]
I really don't remeber the thing, sorry :(

**Comment by bluepuma77** [comment]
Solved. Would be good in README or example.
```
let opHelper = new OperationHelper({
    //...
    xml2jsOptions:  {explicitArray: false}
})
opHelper.execute('ItemSearch', {
    'SearchIndex': 'Books',
    'Keywords': 'harry potter',
    'ResponseGroup': 'ItemAttributes,Offers',
    'ItemPage': '1' // 1-10
}, function (err, results) {
    console.log(JSON.stringify(results, null, 4))                    
})
```
