### ISSUE TITLE
Way to change ENDPOINT

### ISSUE THREAD

**Issue by LeonardoMinatiCrispyBacon** [dmcquay/node-apac#69]
I'm using this awesome module but i need to use IT endpoint. Is there a way to change the endpoint?

This is my code:

```
var util = require('util'),
    OperationHelper = require('apac').OperationHelper;

var opHelper = new OperationHelper({
    awsId: 'XXX',
    awsSecret: 'XXX',
    assocId: 'XXX'
});
```

Thank you for the help!

**Comment by dmcquay** [comment]
Yes. Set locale to 'IT' in the options you pass to OperationHelper.

**Comment by LeonardoMinatiCrispyBacon** [comment]
Thank you so much, awesome job here!

**Comment by dmcquay** [comment]
Thanks!
