### ISSUE TITLE
Missing required HMAC

### ISSUE THREAD

**Issue by resistdesign** [dmcquay/node-apac#70]
When calling `CartAdd` I get an error:

```
"Errors": {
        "Error": {
          "Code": "AWS.MissingParameters",
          "Message": "Your request is missing required parameters. Required parameters include HMAC."
        }
      }
```

`CartCreate` works fine.

**Comment by resistdesign** [comment]
Does `node-apac` generate the `HMAC`?

**Comment by resistdesign** [comment]
Nevermind, it comes back from `CartCreate`, reading is hard! :P

**Comment by dmcquay** [comment]
Thanks for following up and closing this.

**Comment by resistdesign** [comment]
You have no open issues, I didn't want to tarnish the repo ;)
