### ISSUE TITLE
Results returned are in XML format

### ISSUE THREAD

**Issue by johnfoderaro** [dmcquay/node-apac#72]
Firstly, I love this npm module. I was using it several months back on a project and recall that the results would be returned in JSON format (I do not recall which version I was running at that time). I just recently began testing a new project with this module (v 2.0.2) and am now realizing that the results are being returned in the XML format. 

I've checked the docs over and over again and looked through closed issues here on GitHub, just to make sure I wasn't going crazy, imagining things. The closest thing I could find was issue https://github.com/dmcquay/node-apac/issues/45. 

Is there anything specific to do to enable JSON formatted results?

**Comment by francescotonini** [comment]
Honestly I don't remember whether or not we had the possibility to parse the result as JSON (my first implementation of this module was sept. 2015). I know it's not the best solution, but you could use JSON.parse. 

BTW JSON parse would be a nice feature.

**Comment by dmcquay** [comment]
I'm unavailable for a few days, but I'll take a look at this as soon as I
get back.

**Comment by johnfoderaro** [comment]
@dmcquay thank you. I will take a look at the previous project that had used the `apac` npm module. Also, I may be confusing the previous project's results with a JavaScript object instead of JSON. However I do recall needing to use the `util` module to "see" my results in the console during development and do not recall dealing with XML (either way, the module works). Thanks!

**Comment by thaerlabs** [comment]
@johnfoderaro the reponse object resolve from the promise has 2 keys `result` and `responseBody`. *results* is the JSON parsed response, and is the original XML `responseBody`.

**Comment by johnfoderaro** [comment]
@thaerlabs thank you for the clarification. I was looking at the wrong item. As I had a feeling, this wasn't an issue with the module but with the user :)

**Comment by dmcquay** [comment]
Thank you Thaer.
