### ISSUE TITLE
Not working with async/await

### ISSUE THREAD

**Issue by zerbfra** [dmcquay/node-apac#78]
Hi,
`let response = await this.op.execute('ItemLookup', {'ItemId': asin, 'ResponseGroup': 'Large'})`

The code above doesn't wait to complete before continuing execution.
Any help?

Thanks

**Comment by dmcquay** [comment]
I'd need to see more code to tell you what is wrong. Are you executing that statement top level in a file or inside of another function? My hunch is that you're using async wrong, not a problem with node-apac.

**Comment by zerbfra** [comment]
It was an issue realated to an unseen _.each 
Thanks!
