### ISSUE TITLE
No-Cors Error on ItemLookup

### ISSUE THREAD

**Issue by ddeisadz** [dmcquay/node-apac#87]
After calling `client.execute('ItemLookup', ...)` with all the credentials and options, there is a successfull status `200 request` (from console network) but for some reason it prints `Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8888' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` 

What is the best way around this? @dmcquay 

Best,

David

**Comment by dmcquay** [comment]
It sounds like you are trying to call this from the browser. You should not do that.
