### ISSUE TITLE
Does apac support PA-APIv5 ？

### ISSUE THREAD

**Issue by tea3** [dmcquay/node-apac#97]
Does apac support v5?

What's new in Product Advertising API 5.0
https://webservices.amazon.com/paapi5/documentation/?ref_=pe_8930082_379941342

**Comment by newsfusion** [comment]
v5 will not work with this library until someone will update it

**Comment by shubhendusaurabh** [comment]
@dmcquay will this project be updated to v5? v4 is going down in few days?

**Comment by jorgerosal** [comment]
The current solution would be using Amazon [SDK](https://webservices.amazon.com/paapi5/documentation/quick-start/using-sdk.html#nodejs) for the new 5.0 API including node. Alternatively, I created a wrapper that will make the transition a bit easier for nodeJs users.
https://www.npmjs.com/package/amazon-paapi

**Comment by tea3** [comment]
@newsfusion @shubhendusaurabh @jorgerosal 
Thank you :D I have resolved migration to new version using [Amazon official api](https://www.npmjs.com/package/paapi5-nodejs-sdk) .  
https://photo-tea.com/p/1803/amazon-how-to-itemlookup-nodejs/
